#!/bin/bash
# 本地仓库工作流示例

echo "=== 本地 Git 工作流 ==="
echo ""
echo "1. 初始化本地仓库:"
echo "   git init"
echo ""
echo "2. 添加文件到暂存区:"
echo "   git add <文件名>"
echo "   git add .  # 添加所有文件"
echo ""
echo "3. 提交到本地仓库:"
echo "   git commit -m '提交说明'"
echo ""
echo "4. 查看状态和历史:"
echo "   git status"
echo "   git log --oneline"
echo ""
echo "5. 创建分支（本地开发）:"
echo "   git branch <分支名>"
echo "   git checkout <分支名>"
echo "   # 或: git checkout -b <分支名>"
echo ""
echo "✅ 所有操作都在本地完成，不需要网络"
