#!/bin/bash
# 远程仓库协作工作流示例

echo "=== 远程 GitHub 协作工作流 ==="
echo ""
echo "1. 关联远程仓库:"
echo "   git remote add origin https://github.com/username/repo.git"
echo ""
echo "2. 推送到远程:"
echo "   git push -u origin main"
echo ""
echo "3. 获取远程更新:"
echo "   git pull origin main"
echo ""
echo "4. 创建 Pull Request（GitHub 网页）:"
echo "   - 推送分支: git push origin feature-branch"
echo "   - 在 GitHub 上点击 'Compare & pull request'"
echo "   - 填写 PR 描述，请求代码审查"
echo ""
echo "5. 合并代码:"
echo "   - 审查通过后点击 'Merge pull request'"
echo "   - 或命令行: git merge feature-branch"
echo ""
echo "6. GitHub Actions 自动化:"
echo "   - 自动测试、部署"
echo "   - 配置文件: .github/workflows/*.yml"
echo ""
echo "✅ 支持多人协作、代码审查、自动化"
